"""empty message

Revision ID: 19818a9209c4
Revises: d444165f938e
Create Date: 2020-09-07 19:57:20.202063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19818a9209c4'
down_revision = 'd444165f938e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping')
    # ### end Alembic commands ###
