"""empty message

Revision ID: b1c41d58a7b8
Revises: 19818a9209c4
Create Date: 2020-09-10 11:34:23.168645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c41d58a7b8'
down_revision = '19818a9209c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product', sa.VARCHAR(length=50), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
