"""empty message

Revision ID: d444165f938e
Revises: 834c525f2df6
Create Date: 2020-09-07 19:14:12.963631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd444165f938e'
down_revision = '834c525f2df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'quantity')
    # ### end Alembic commands ###
